version: "3.1"

services:
  gobarber_db:
    image: postgres
    container_name: gostack_gobarber
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobarber
    ports:
      - 5432:5432

  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
